title: Frincy Clement # your name (or website title) here
logo: "/images/fc-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A well-rounded Artificial Intelligence enthusiast with business know-how and expertise in AI. 
  <br><br>
  With over 7 years of experience in AI, Business and Analytics , Frincy is a self-motivated, organized and meticulous engineer, who always keeps the overarching goal in focus.
  <br><br>
  <a href="https://www.linkedin.com/in/frincyclement/">View My LinkedIn Profile</a>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-180707822-1 # your Google Analytics tracking ID here
