title: Frincy Clement # your name (or website title) here
logo: "/images/frincyc.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Engineer
  <br><br>
  MSc. CS, MBA, B.Tech  
  <br><br>
  <a href="https://www.linkedin.com/in/frincyclement/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
