title: Frincy Clement # your name (or website title) here
logo: "/images/fc-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A well-rounded Artificial Intelligence enthusiast with business know-how and expertise in AI. Currently working as a Machine Learning Engineer at AltaML Inc. 
  <br><br>
  With over 6+ years of experience, Frincy is a self-motivated, organized and meticulous engineer, always keeping the overrching goal in focus.
  <br><br>
  <a href="https://www.linkedin.com/in/frincyclement/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-180707822-1 # your Google Analytics tracking ID here
